#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
#服务的名称
spring:
  #消息队列
  rabbitmq:
    host: 192.168.0.105
    port: 5672
    username: guest
    password: guest
    #zipkin服务所在地址
  zipkin:
    base-url: http://localhost:9411/
  #配置采样百分比,开发环境可以设置为1，表示全部，生产就用默认
  sleuth:
    sampler:
      probability: 1  
      
#暴露全部的监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"        
      
