#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
#服务的名称
spring:
  #消息队列
  rabbitmq:
    host: 192.168.0.105
    port: 5672
    username: guest
    password: guest
#暴露全部的监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"        
      
