server:
  port: 8781

#服务的名称
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 2000

#修改调用超时时间
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 4000
        readTimeout: 4000

#设置超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000
